// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhikrcoimgaqbclhoqap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoaWtyY29pbWdhcWJjbGhvcWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODkwODMsImV4cCI6MjA3MjM2NTA4M30.YuD6yDMD_lU45zu2LEK4gAA19cDG4VIShq6JGkyx6_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});